name: super_to_do
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_riverpod: 2.1.1
  freezed_annotation: 2.1.0
  go_router: 6.0.1
  http_mock_adapter: ^0.3.3
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  path_provider: 2.0.11
  pretty_dio_logger: ^1.1.1
  pull_to_refresh: ^2.0.0
  retrofit: ^3.3.1
  rxdart: ^0.27.7
  sembast: ^3.3.1+1
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: 2.2.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.1.0+1
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true

  assets:
    # Add all product images
    - assets/images/
